name: "docker action"
description: "does auth, build and push"
author: "Tradeshift"
inputs:
  build-args:
    required: false
    description: list of build args
  builder:
    required: false
    description: buildx builder to use
  context:
    required: false
    description: docker context
    default: .
  file:
    required: false
    description: path to dockerfile
  labels:
    required: false
    description: list of labels
  load:
    required: false
    description: wether to load the image in the docker deamon
  password:
    required: false
    description: >
      Password for docker registry detected from the repository.
  docker-hub-password:
    required: true
    description: Password of tradeshiftops user in Docker Hub
    default: ${{ secrets.DOCKER_HUB_PASSWORD }}
  push:
    required: false
    description: wether to push or not
    default: true
  platform:
    required: false
    description: list of architectures to build against
  repo-cache:
    required: false
    description: use repo cache (actions/cache) for docker layers
    default: false
  repo-cache-key:
    required: false
    description: use this to invalidate existing cache
    default: buildx
  repository:
    required: false
    description: >
      The repository where default tags will be pushed. If not specified this
      will default to eu.gcr.io/tradeshift-base/<repo-name>
  registries:
    required: false
    description: >
      A mulitline string with registries to login to
  tags:
    required: false
    description: list of tags
  username:
    required: false
    description: >
      Username for docker registry detected from the repository.
    default: _json_key
  auth-only:
    required: false
    description: >
      This flag can be used in case only authentication against docker 
      repo is needed
    default: "false"
  skip-default-tag:
    required: false
    description: >
      This flag can be used to disable automatically tagging the image with the SHA.
      Skipping default tag requires specifying alternative tags.
  useqemu:
    required: false
    description: >
      This flag can be used to enable Qemu, which is used for multi architecture builds like arm
    default: "false"
outputs:
  builder:
    description: buildx builder name
  image:
    description: full image name including git SHA tag
runs:
  using: "node16"
  main: "dist/index.js"
  post: "dist/index.js"
