name: 'master'
on:
  push:
    branches:
      - dist-update-test # TODO: Fix this back to master

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      needs-update: ${{ steps.diff.output != 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - run: |
          npm ci
          npm run build
          npm run format-check
          npm run lint
          npm run package
          npm run test
      - name: Check for changes (fail if we forgot to update dist)
        run: git diff --quiet dist
        id: diff
        continue-on-error: true

      - name: Set up commit signing w/ GPG
        if: ${{ steps.diff.outcome != 'success' }}
        id: configure
        run: |
          KEYDIR=$(mktemp -d)
          KEYFILE="${KEYDIR}/key.asc"
          echo "$GPG_KEY" > "${KEYFILE}"
          GPG_SHORTID=$(gpg --show-keys --keyid-format=long "${KEYFILE}" | grep sec | cut -d/ -f2 | cut -d' ' -f1)
          gpg --import --batch --yes "${KEYFILE}"
          git config --global commit.gpgsign true
          git config --global user.signingkey "${GPG_SHORTID}"
          # Get the email and username of the key:
          GPG_USER=$(gpg --fingerprint "${GPG_SHORTID}" | sed -n '/^uid/s/.*\]\s//p')
          _GPG_EMAIL=${GPG_USER#*\<}
          GPG_EMAIL=${_GPG_EMAIL%>}
          git config --global user.email ${GPG_EMAIL}
          git config --global user.name ${GPG_USER%<*}

          echo "::set-output name=user::${GPG_USER}"
        env:
          GPG_KEY: ${{ secrets.TRADESHIFTCI_GPG_KEY }}
      
      - name: PR build changes if needed
        uses: tradeshift/create-pull-request@v3
        if: ${{ steps.diff.outcome != 'success' }}
        with:
          commit-message: "build: update dist folder"
          branch: release-update-dist
          title: "Update for release: update package runtime"
          body: |
            This PR is created automatically because the repo has been changed
            without updating the packaged version in the `dist` folder.

            Before these changes can be released, the `dist` folder has to be
            updated. By merging this when the build is green, a new release
            will be created based on the list of changes since the last release.

            For more info see [semantic-release.gitbook.io/semantic-release/](https://semantic-release.gitbook.io/semantic-release/)

          token: ${{ secrets.GH_TOKEN }}
          committer: ${{ steps.configure.outputs.user }}
          author: ${{ steps.configure.outputs.user }}
          draft: true

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ needs.build.outputs.needs-update != 'true' }}
    steps:
      - uses: actions/checkout@v2
      - uses: tradeshift/actions-semantic-release@v1
        id: semantic-release
        with:
          check_name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Action tags (major version tag)
        if: ${{ steps.semantic-release.outputs.new_release_published }}
        run: |
          git tag -f v${{ steps.semantic-release.outputs.new_release_major_version }}
          git push -f origin v${{ steps.semantic-release.outputs.new_release_major_version }}
